backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "artikel"
    label: "Artikel & Promo"
    folder: "content/artikel"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul Promo", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Foto Unit", name: "image", widget: "image"}
      - {label: "Spesifikasi & Penawaran", name: "body", widget: "markdown"}
