backend:
  name: git-gateway
  branch: main # pastikan sesuai nama branch di GitHub Anda

media_folder: "assets/images" 
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Artikel & Promo"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul Artikel", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Gambar Unit", name: "featured_image", widget: "image"}
      - {label: "Isi Artikel (Spek/Promo)", name: "body", widget: "markdown"}
